### ISSUE TITLE
Docs for http client?

### ISSUE THREAD

**Issue by dazinator** [fs7744/Norns.Urd#25]
Just exploring your projects, looks really good, and could be very useful, nice work!

It would be good to have some docs for the http client functionality. Which features can it cope with:-

1. Multipart requests?
2. File Uploads? IFormFile ?
3. All different verbs (POST, PUT, PATCH etc)
4. Cancellation tokens?
5. Use of Polly - retry?
6. Use of Cache on GET methods to avoid making http call?
7. Multipart responses?
8. File downloads?

**Comment by fs7744** [comment]
Thanks (*^_^*)

For Polly and Cache has been already supported.  
You can see doc on [https://fs7744.github.io/Norns.Urd/index.html](https://fs7744.github.io/Norns.Urd/index.html )

HttpClilent is in progress.
First version will support these : 

- All different verbs (POST, PUT, PATCH etc)
- json
- xml
- route parameters
- class to query string
- out parameter to get response header
- doc will be add after first version ready

After done these will add features if someone want to use , like your :

- IFormFile 
- upload by stream
- download by stream
- Cancellation tokens
- Multipart/form-data
- and more

**Comment by fs7744** [comment]
add httpclient doc on  https://fs7744.github.io/Norns.Urd/index.html#httpclient

if you have any issue, just create it (*^_^*)
