### ISSUE TITLE
autofac 下不生效

### ISSUE THREAD

**Issue by timself6** [fs7744/Norns.Urd#29]
builder.Host.UseServiceProviderFactory(new AutofacServiceProviderFactory())
            .ConfigureContainer<ContainerBuilder>((hostBuilderContext, containerBuilder) =>
            {

            });

**Comment by fs7744** [comment]
未使用过autofac， 有相关具体demo吗？

**Comment by yuzd** [comment]
> 未使用过autofac， 有相关具体demo吗？
我之前整理过，可以参考
https://github.com/yuzd/Autofac.Annotation/wiki/0.QucikStart

**Comment by fs7744** [comment]
use autofac test https://github.com/fs7744/Norns.Urd/blob/main/test/Norns.Urd.Test/DependencyInjection/AutofacTest.cs
no problem
if still has problem , reopen this issue and upload a demo project
