### ISSUE TITLE
How to use with simple injector?

### ISSUE THREAD

**Issue by thiago-molive** [fs7744/Norns.Urd#32]
Hi, i'm testing Aspect Retry Attribute functionality.

How can i use it with simple injector?

**Comment by fs7744** [comment]
only support  IServiceCollection now,  

but you can add to IServiceCollection first 

then convert IServiceCollection to simple injector  

like the autofac code :  
https://github.com/fs7744/Norns.Urd/blob/main/test/Norns.Urd.Test/DependencyInjection/AutofacTest.cs
