### ISSUE TITLE
.NET 8.0 Asp.Versioning.Mvc and ConfigureAop, IApiVersionParser.TryParse(ReadOnlySpan) error

### ISSUE THREAD

**Issue by robertgm** [fs7744/Norns.Urd#33]
I have `Norns.Urd v.0.0.4.7` and installed `Asp.Versioning.Mvc` in version `8.1.0`.
When I add `builder.Services.ConfigureAop();` in Program.cs application throws exception when it try to reach any endpoint
that require api version.
For example, for endpoint
`http://localhost:5253/v1/weatherforecast`
it throws exception:
```
An unhandled exception occurred while processing the request.
InvalidProgramException: Common Language Runtime detected an invalid program.
Norns.Urd.DynamicProxy.Generated.ApiVersionParser_Proxy_Inherit.Asp.Versioning.IApiVersionParser.TryParse(ReadOnlySpan<char> text, out ApiVersion apiVersion)
```
Stack:
```
InvalidProgramException: Common Language Runtime detected an invalid program.
Norns.Urd.DynamicProxy.Generated.ApiVersionParser_Proxy_Inherit.Asp.Versioning.IApiVersionParser.TryParse(ReadOnlySpan<char> text, out ApiVersion apiVersion)
Asp.Versioning.Routing.ApiVersionRouteConstraint.Match(HttpContext httpContext, IRouter route, string routeKey, RouteValueDictionary values, RouteDirection routeDirection)
Microsoft.AspNetCore.Routing.Matching.DfaMatcher.ProcessConstraints(Endpoint endpoint, KeyValuePair<string, IRouteConstraint>[] constraints, HttpContext httpContext, RouteValueDictionary values)
Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

Steps to reproduce
Application ASP.NET Core Web API generated from template in Visual Studio with `.NET 8.0`.
To application we have to add two nuget packages:

- Asp.Versioning.Mvc in version 8.1.0
- Norns.Urd in version 0.0.4.7

Next, in Program.cs file add below lines:
```
builder.Services.AddApiVersioning(options =>
{
    options.ReportApiVersions = true;
    options.AssumeDefaultVersionWhenUnspecified = true;
    options.DefaultApiVersion = new ApiVersion(1, 0);
});
```

and:
`builder.Services.ConfigureAop();`

in this way (between AddControllers and builder.Build()):
```
builder.Services.AddControllers();
builder.Services.AddApiVersioning(options =>
{
    options.ReportApiVersions = true;
    options.AssumeDefaultVersionWhenUnspecified = true;
    options.DefaultApiVersion = new ApiVersion(1, 0);
});
builder.Services.ConfigureAop();
var app = builder.Build();
```
In `WeatherForecastController` comment `[Route("[controller]")]` attribute and add two attributes like that:
```
[ApiController]
[ApiVersion("1.0")]
[Route("v{version:apiVersion}/[controller]")]
//[Route("[controller]")]
public class WeatherForecastController : ControllerBase
{
```

Start application and change in browser the url from
`http://localhost:5253/weatherforecast`  (generated automatically)
to this one:
`http://localhost:5253/v1/weatherforecast`

Application will start and throw exception.

Repository with example of application to reproduce bug:
https://github.com/robertgm/VersioningMvcAopBug

**Comment by fs7744** [comment]
just ingore aop for asp

builder.Services.ConfigureAop(i => i.NonPredicates.AddNamespace("Asp*"));
